# Generated by Django 5.0.1 on 2024-01-10 11:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('position_nr', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be greater than or equal to 1.'), django.core.validators.MaxValueValidator(limit_value=140, message='Value must be less than or equal to 140.')])),
            ],
        ),
        migrations.CreateModel(
            name='WorkZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Recive', 'Recive'), ('Storage', 'Storage'), ('Shipment', 'Shipment')], max_length=10)),
                ('way_index', models.IntegerField(choices=[(1, 'Recive'), (2, 'Storage'), (3, 'Shipment')])),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('supplier_id', models.CharField(max_length=40)),
            ],
            options={
                'unique_together': {('name', 'supplier_id')},
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_order', models.IntegerField()),
                ('ssc_barcode', models.CharField(max_length=20)),
                ('images_url', models.ImageField(upload_to='images/')),
                ('date_recive', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('identifier', models.IntegerField(default=20240110481, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='delivery.location')),
                ('recive_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recive_location', to='delivery.location')),
                ('supplier_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='work_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.workzone'),
        ),
    ]
