# Generated by Django 5.2.5 on 2025-08-30 15:03

import delivery.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_prefix', models.CharField(blank=True, max_length=50)),
                ('image_data', models.ImageField(upload_to=delivery.models.custom_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('work_zone', models.IntegerField(choices=[(1, 'Recive'), (2, 'Storage'), (3, 'Ready to load'), (4, 'Utilization'), (4, 'Shiped'), (4, 'Cancel'), (4, 'Transfer')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReasoneComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('position_nr', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be greater than or equal to 1.'), django.core.validators.MaxValueValidator(limit_value=140, message='Value must be less than or equal to 140.')])),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('supplier_wms_id', models.CharField(max_length=40)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'supplier_wms_id'), name='unique_supplier_wms_id')],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_order', models.CharField(max_length=40, null=True)),
                ('sscc_barcode', models.CharField(max_length=20, null=True)),
                ('date_recive', models.DateTimeField()),
                ('comment', models.TextField()),
                ('identifier', models.BigIntegerField(unique=True)),
                ('office_chek', models.BooleanField(default=False)),
                ('extra_comment', models.CharField(blank=True, max_length=255)),
                ('transaction', models.TextField(blank=True)),
                ('complite_status', models.BooleanField(default=False)),
                ('download_images_status', models.BooleanField(default=False)),
                ('lovo_link', models.TextField(blank=True, null=True)),
                ('lovo_name', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('images_url', models.ManyToManyField(blank=True, to='delivery.imagemodel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='delivery.location')),
                ('recive_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recive_location', to='delivery.location')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.shop')),
                ('supplier_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.supplier')),
            ],
        ),
    ]
