# Generated by Django 5.0.1 on 2024-01-14 19:47

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='identifier',
            field=models.IntegerField(default=20240114789, unique=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image_data',
            field=models.ImageField(upload_to=delivery.models.custom_upload_path),
        ),
    ]
