# Generated by Django 5.0.1 on 2024-01-10 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='delivery.location'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='recive_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recive_location', to='delivery.location'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('name', 'supplier_id')},
        ),
        migrations.AddField(
            model_name='delivery',
            name='supplier_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.supplier'),
        ),
        migrations.AddField(
            model_name='location',
            name='work_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.workzone'),
        ),
    ]
