# Generated by Django 5.0.1 on 2024-01-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasoneComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='delivery',
            name='identifier',
            field=models.IntegerField(default=20240111182, unique=True),
        ),
    ]
