# Generated by Django 5.0.1 on 2024-01-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_delivery_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='identifier',
            field=models.IntegerField(default=20240115525, unique=True),
        ),
    ]
