# Generated by Django 5.0.1 on 2024-01-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_reasonecomment_alter_delivery_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_id',
            new_name='supplier_wms_id',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='identifier',
            field=models.IntegerField(default=20240112920, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('name', 'supplier_wms_id')},
        ),
    ]
