# Generated by Django 5.0.1 on 2024-01-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_rename_supplier_id_supplier_supplier_wms_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='identifier',
            field=models.IntegerField(default=20240112430, unique=True),
        ),
    ]
