# Generated by Django 5.0.1 on 2024-01-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_identifier_alter_delivery_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date_recive',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='identifier',
            field=models.BigIntegerField(default=202401267884, unique=True),
        ),
    ]
