# Generated by Django 5.0.1 on 2024-02-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0005_alter_delivery_date_recive_alter_delivery_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="identifier",
            field=models.BigIntegerField(unique=True),
        ),
    ]
