# Generated by Django 5.0.1 on 2024-02-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0007_alter_location_work_zone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkZone",
        ),
    ]
