# Generated by Django 5.0.1 on 2024-02-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0008_delete_workzone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="date_recive",
            field=models.DateTimeField(),
        ),
    ]
