# Generated by Django 5.0.1 on 2024-02-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0009_alter_delivery_date_recive"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="excra_comment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="delivery",
            name="office_chek",
            field=models.BooleanField(default=False),
        ),
    ]
