# Generated by Django 5.0.1 on 2024-02-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0010_delivery_excra_comment_delivery_office_chek"),
    ]

    operations = [
        migrations.RenameField(
            model_name="delivery",
            old_name="excra_comment",
            new_name="extra_comment",
        ),
    ]
