# Generated by Django 5.0.1 on 2024-02-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0011_rename_excra_comment_delivery_extra_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="transaction",
            field=models.TextField(blank=True),
        ),
    ]
