# Generated by Django 5.0.1 on 2024-02-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0012_delivery_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="work_zone",
            field=models.IntegerField(
                choices=[
                    (1, "Recive"),
                    (2, "Storage"),
                    (3, "Ready to load"),
                    (4, "Utilization"),
                    (4, "Shiped"),
                ],
                default=1,
            ),
        ),
    ]
