# Generated by Django 5.0.1 on 2024-02-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0014_delivery_complite_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="supplier",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                fields=("name", "supplier_wms_id"), name="unique_supplier_wms_id"
            ),
        ),
    ]
