# Generated by Django 5.0.1 on 2024-03-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0015_alter_supplier_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
