# Generated by Django 5.0.1 on 2024-04-03 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0016_alter_location_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="nr_order",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="delivery.shop",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="sscc_barcode",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="work_zone",
            field=models.IntegerField(
                choices=[
                    (1, "Recive"),
                    (2, "Storage"),
                    (3, "Ready to load"),
                    (4, "Utilization"),
                    (4, "Shiped"),
                    (4, "Cancel"),
                ],
                default=1,
            ),
        ),
    ]
