# Generated by Django 5.0.1 on 2024-04-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0017_alter_delivery_nr_order_alter_delivery_shop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="download_images_status",
            field=models.BooleanField(default=False),
        ),
    ]
