# Generated by Django 5.0.1 on 2024-06-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0018_delivery_download_images_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="lovo_link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="lovo_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="work_zone",
            field=models.IntegerField(
                choices=[
                    (1, "Recive"),
                    (2, "Storage"),
                    (3, "Ready to load"),
                    (4, "Utilization"),
                    (4, "Shiped"),
                    (4, "Cancel"),
                    (4, "Transfer"),
                ],
                default=1,
            ),
        ),
    ]
